### ISSUE TITLE
[Front] init setting

### ISSUE THREAD

**Issue by hzoou** [Nexters/colletter#15]
## 초기 설정
* colletter/front/colleter/public 에서 oAuth.js 넣기 
* 경로 colletter/front/colleter 에서 수행
  - yarn
  - yarn add router
  - yarn add styled-components
  - yarn add react-router-dom
  - yarn start

**Comment by wkdtndgns** [comment]
yarn add react-bootstrap

**Comment by hzoou** [comment]
- yarn add react-admin
- yarn add ra-data-json-server

**Comment by wkdtndgns** [comment]
yarn add axios

**Comment by wkdtndgns** [comment]
yarn add react-google-login

**Comment by hzoou** [comment]
yarn add url-search-params-polyfill 
yarn add react-facebook-login
